import { useCallback, useEffect, useMemo, useState } from 'react'
import { Search, X, Save, LogOut, ClipboardList, Users, UserRound } from 'lucide-react'
import { useAuth } from '../components/AuthGuard'
import { useToast } from '../components/UI'
import { HelperAPI } from '../lib/helper'
import { filterCustomers, customerSecondaryLabel, getCustomerPhoneLast2 } from '../lib/customerSearch'
import QuantityInput from '../components/QuantityInput'

function itemPrice(item){const opt=(item.product.price_options||[]).find(o=>o.label===item.spec?.package);return Number(opt?.price??item.product.price??0)}
function validateItem(x){if(!x)return'請先選擇商品';if((x.product.price_options||[]).length&&!x.spec.package)return`「${x.product.name}」請選組合／包裝`;if((x.product.spec_flavors||[]).length&&!x.spec.flavor)return`「${x.product.name}」請選口味`;if(['color_size','color_free','color_only'].includes(x.product.spec_mode)&&!x.spec.color)return`「${x.product.name}」請選顏色`;if(['color_size','size_only'].includes(x.product.spec_mode)&&!x.spec.size)return`「${x.product.name}」請選尺寸`;return''}
function ProductSpecs({item,onSpec}){if(!item)return null;const p=item.product,s=item.spec||{};return <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{(p.price_options||[]).length>0&&<select value={s.package||''} onChange={e=>onSpec('package',e.target.value)}><option value="">選組合／包裝 *</option>{p.price_options.map(o=><option key={o.label} value={o.label}>{o.label}｜NT${Number(o.price||0).toLocaleString()}</option>)}</select>}{(p.spec_flavors||[]).length>0&&<select value={s.flavor||''} onChange={e=>onSpec('flavor',e.target.value)}><option value="">選口味 *</option>{p.spec_flavors.map(v=><option key={v}>{v}</option>)}</select>}{['color_size','color_free','color_only'].includes(p.spec_mode)&&<select value={s.color||''} onChange={e=>onSpec('color',e.target.value)}><option value="">選顏色 *</option>{(p.spec_colors||[]).map(v=><option key={v}>{v}</option>)}</select>}{['color_size','size_only'].includes(p.spec_mode)&&<select value={s.size||''} onChange={e=>onSpec('size',e.target.value)}><option value="">選尺寸 *</option>{(p.spec_sizes||[]).map(v=><option key={v}>{v}</option>)}</select>}</div>}

export default function HelperPortal(){
  const { user,account,logout }=useAuth(); const toast=useToast()
  const[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[entries,setEntries]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const[mode,setMode]=useState('customer')

  const[customerSearch,setCustomerSearch]=useState(''),[customer,setCustomer]=useState(null),[items,setItems]=useState([]),[productSearch,setProductSearch]=useState(''),[productOpen,setProductOpen]=useState(false),[isVirtual,setIsVirtual]=useState(false),[note,setNote]=useState('')

  const[batchProduct,setBatchProduct]=useState(null),[batchProductSearch,setBatchProductSearch]=useState(''),[batchProductOpen,setBatchProductOpen]=useState(false),[batchCustomerSearch,setBatchCustomerSearch]=useState(''),[batchCustomerOpen,setBatchCustomerOpen]=useState(false),[batchRows,setBatchRows]=useState([]),[batchVirtual,setBatchVirtual]=useState(false),[batchNote,setBatchNote]=useState('')

  const load=useCallback(async()=>{setLoading(true);try{const[c,p,e]=await Promise.all([HelperAPI.customers(),HelperAPI.catalog(),HelperAPI.myEntries(user.uid)]);setCustomers(c);setProducts(p);setEntries(e)}catch(err){toast('載入失敗：'+err.message,'error')}finally{setLoading(false)}},[user,toast])
  useEffect(()=>{if(user)load()},[user,load])

  const custs=useMemo(()=>filterCustomers(customers,customerSearch).slice(0,20),[customers,customerSearch])
  const batchCusts=useMemo(()=>filterCustomers(customers,batchCustomerSearch).slice(0,30),[customers,batchCustomerSearch])
  const productMatches=(search)=>{const q=search.trim().toLowerCase();return products.filter(p=>!q||String(p.name||'').toLowerCase().includes(q)).slice(0,30)}
  const prods=useMemo(()=>productMatches(productSearch),[products,productSearch])
  const batchProds=useMemo(()=>productMatches(batchProductSearch),[products,batchProductSearch])

  function addProduct(product){setItems(p=>[...p,{product,qty:1,spec:{package:'',flavor:'',color:'',size:''},note:''}]);setProductSearch('');setProductOpen(false)}
  function patchItem(i,patch){setItems(p=>p.map((x,n)=>n===i?{...x,...patch}:x))}
  function patchSpec(i,key,value){setItems(p=>p.map((x,n)=>n===i?{...x,spec:{...x.spec,[key]:value}}:x))}

  async function saveCustomerMode(){if(!customer){toast('請先選擇客戶','error');return}if(!items.length){toast('請至少加入一項商品','error');return}for(const x of items){if(!Number.isInteger(Number(x.qty))||Number(x.qty)<1){toast('數量至少為 1','error');return}const err=validateItem(x);if(err){toast(err,'error');return}}
    setSaving(true);try{const cleanItems=items.map(x=>({product_id:x.product.id,product_name:x.product.name,sale_price:itemPrice(x),qty:Number(x.qty),spec:x.spec,note:x.note||''}));await HelperAPI.createEntry({created_by_uid:user.uid,created_by_name:account?.display_name||user.email||'',customer_id:customer.id,customer_name:customer.name,customer_phone_last2:getCustomerPhoneLast2(customer),items:cleanItems,total_amount:cleanItems.reduce((s,x)=>s+x.sale_price*x.qty,0),is_virtual:isVirtual,note:note.trim()});toast('登記完成 ✓');setCustomer(null);setCustomerSearch('');setItems([]);setIsVirtual(false);setNote('');await load()}catch(err){toast('登記失敗：'+err.message,'error')}finally{setSaving(false)}}

  function chooseBatchProduct(product){if(batchRows.length&&!window.confirm('更換商品會清除目前已加入的客戶清單，確定要更換嗎？'))return;setBatchProduct({product,qty:1,spec:{package:'',flavor:'',color:'',size:''},note:''});setBatchRows([]);setBatchProductSearch('');setBatchProductOpen(false)}
  function patchBatchSpec(key,value){setBatchProduct(p=>p?{...p,spec:{...p.spec,[key]:value}}:p)}
  function addBatchCustomer(c){if(!batchProduct){toast('請先選擇商品','error');return}const err=validateItem(batchProduct);if(err){toast(err,'error');return}if(batchRows.some(r=>r.customer.id===c.id)){toast(`${c.name} 已在清單中`,'error');return}setBatchRows(rows=>[...rows,{customer:c,qty:1,note:''}]);setBatchCustomerSearch('');setBatchCustomerOpen(true)}
  function patchBatchRow(id,patch){setBatchRows(rows=>rows.map(r=>r.customer.id===id?{...r,...patch}:r))}
  async function saveBatch(){if(!batchProduct){toast('請先選擇商品','error');return}const err=validateItem(batchProduct);if(err){toast(err,'error');return}if(!batchRows.length){toast('請至少加入一位客戶','error');return}for(const r of batchRows){if(!Number.isInteger(Number(r.qty))||Number(r.qty)<1){toast(`${r.customer.name} 的數量至少為 1`,'error');return}}
    const price=itemPrice(batchProduct);const commonItem={product_id:batchProduct.product.id,product_name:batchProduct.product.name,sale_price:price,spec:batchProduct.spec}
    const payloads=batchRows.map(r=>({created_by_uid:user.uid,created_by_name:account?.display_name||user.email||'',customer_id:r.customer.id,customer_name:r.customer.name,customer_phone_last2:getCustomerPhoneLast2(r.customer),items:[{...commonItem,qty:Number(r.qty),note:r.note||''}],total_amount:price*Number(r.qty),is_virtual:batchVirtual,note:batchNote.trim()}))
    setSaving(true);try{const count=await HelperAPI.createEntries(payloads);toast(`已一次送出 ${count} 筆登記 ✓`);setBatchRows([]);setBatchCustomerSearch('');setBatchVirtual(false);setBatchNote('');await load()}catch(e){toast('批次登記失敗：'+e.message,'error')}finally{setSaving(false)}}

  const total=items.reduce((s,x)=>s+itemPrice(x)*Number(x.qty||0),0)
  const batchTotal=batchProduct?batchRows.reduce((s,r)=>s+itemPrice(batchProduct)*Number(r.qty||0),0):0
  const renderProductList=(list,search,onPick)=>products.length===0?<div style={{padding:'16px 14px',color:'#b45309',background:'#fffbeb',fontSize:13,fontWeight:700}}>⚠ 尚未同步商品目錄，請通知管理員重新同步商品。</div>:list.length===0?<div style={{padding:'16px 14px',color:'var(--text-muted)',fontSize:13}}>找不到符合「{search}」的商品</div>:list.map(p=><button key={p.id} onClick={()=>onPick(p)} style={{display:'flex',width:'100%',justifyContent:'space-between',gap:12,padding:'12px 14px',border:0,borderBottom:'1px solid var(--border)',background:'#fff',cursor:'pointer',textAlign:'left'}}><span style={{fontWeight:700}}>{p.name}</span><strong style={{whiteSpace:'nowrap'}}>NT${Number(p.price||0).toLocaleString()}</strong></button>)

  return <div style={{minHeight:'100vh',background:'#f8fafc'}}><header style={{position:'sticky',top:0,zIndex:20,background:'#0f172a',color:'#fff',padding:'12px 16px',display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><strong style={{fontSize:18}}>📝 小幫手團購登記</strong><div style={{fontSize:11,opacity:.6}}>{account?.display_name||user?.email}</div></div><button onClick={logout} style={{border:'1px solid rgba(255,255,255,.2)',background:'transparent',color:'#fff',borderRadius:8,padding:'8px 10px'}}><LogOut size={14}/> 登出</button></header><main style={{maxWidth:950,margin:'0 auto',padding:16}}>
    <div style={{background:'#ecfdf5',border:'1px solid #a7f3d0',padding:'10px 12px',borderRadius:10,marginBottom:14,fontSize:13,color:'#065f46'}}>此頁只提供客戶查詢與訂單登記</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,marginBottom:14}}><button onClick={()=>setMode('customer')} style={{padding:14,borderRadius:12,border:`2px solid ${mode==='customer'?'var(--indigo)':'var(--border)'}`,background:mode==='customer'?'var(--indigo-light)':'#fff',fontWeight:900,cursor:'pointer'}}><UserRound size={16}/> 依客戶打單<div style={{fontSize:11,fontWeight:500,marginTop:4,color:'var(--text-secondary)'}}>一位客戶可加入多項商品</div></button><button onClick={()=>setMode('product')} style={{padding:14,borderRadius:12,border:`2px solid ${mode==='product'?'var(--emerald)':'var(--border)'}`,background:mode==='product'?'var(--emerald-light)':'#fff',fontWeight:900,cursor:'pointer'}}><Users size={16}/> 依商品連續打單<div style={{fontSize:11,fontWeight:500,marginTop:4,color:'var(--text-secondary)'}}>同一商品連續登記多位客戶</div></button></div>

    {mode==='customer'?<>
      <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>① 選擇客戶</strong></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="姓名／手機末兩碼／Line／FB" style={{paddingLeft:36,height:48,fontSize:16}}/></div>{customerSearch&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden'}}>{custs.map(c=><button key={c.id} onClick={()=>{setCustomer(c);setCustomerSearch('')}} style={{display:'block',width:'100%',textAlign:'left',padding:'10px 12px',border:0,borderBottom:'1px solid var(--border)',background:'#fff'}}><strong>{c.name}</strong><div style={{fontSize:11,color:'var(--text-muted)'}}>{customerSecondaryLabel(c)||'無其他辨識資料'}</div></button>)}</div>}{customer&&<div style={{marginTop:10,padding:12,borderRadius:10,background:'var(--indigo-light)',display:'flex',justifyContent:'space-between'}}><strong>👤 {customer.name}{getCustomerPhoneLast2(customer)?`（末碼 ${getCustomerPhoneLast2(customer)}）`:''}</strong><button onClick={()=>setCustomer(null)} style={{border:0,background:'transparent'}}><X size={16}/></button></div>}</div></div>
      <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>② 加入商品</strong></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input value={productSearch} onFocus={()=>setProductOpen(true)} onClick={()=>setProductOpen(true)} onChange={e=>{setProductSearch(e.target.value);setProductOpen(true)}} placeholder="點選或輸入商品名稱" style={{paddingLeft:36,height:48,fontSize:16}}/></div>{productOpen&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden',background:'#fff',maxHeight:320,overflowY:'auto',boxShadow:'0 10px 28px rgba(15,23,42,.12)'}}>{renderProductList(prods,productSearch,addProduct)}</div>}{items.map((x,i)=><div key={i} style={{marginTop:10,padding:12,border:'1px solid var(--border)',borderRadius:10,background:'#fff'}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong style={{flex:1}}>{x.product.name}</strong><QuantityInput value={x.qty} min={1} onChange={v=>patchItem(i,{qty:v})} style={{width:90,height:44,fontSize:18,fontWeight:900}}/><button onClick={()=>setItems(p=>p.filter((_,n)=>n!==i))} style={{border:0,background:'transparent',color:'var(--rose)'}}><X size={16}/></button></div><ProductSpecs item={x} onSpec={(k,v)=>patchSpec(i,k,v)}/><input value={x.note} onChange={e=>patchItem(i,{note:e.target.value})} placeholder="商品備註" style={{marginTop:8,maxWidth:220}}/></div>)}</div></div>
      <div className="card" style={{marginBottom:14}}><div className="card-body"><label style={{display:'flex',gap:10,padding:12,border:'2px solid #fb7185',borderRadius:10,background:isVirtual?'#fff1f2':'#fff'}}><input type="checkbox" checked={isVirtual} onChange={e=>setIsVirtual(e.target.checked)}/><span><strong style={{color:'#be123c'}}>⚠ 虛擬訂單</strong><div style={{fontSize:11,color:'var(--text-secondary)'}}>客戶尚未完全確定時勾選；不會計入實際訂貨量。</div></span></label><div className="form-group" style={{marginTop:12}}><label>備註</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：客戶晚點確認"/></div><div style={{textAlign:'right',fontSize:20,fontWeight:900,marginBottom:10}}>合計 NT${total.toLocaleString()}</div><button className="btn btn-primary" onClick={saveCustomerMode} disabled={saving} style={{width:'100%',justifyContent:'center',height:50,fontSize:16}}><Save size={16}/>{saving?'儲存中...':'送出登記'}</button></div></div>
    </>:<>
      <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>① 先選商品與規格</strong></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input value={batchProductSearch} onFocus={()=>setBatchProductOpen(true)} onClick={()=>setBatchProductOpen(true)} onChange={e=>{setBatchProductSearch(e.target.value);setBatchProductOpen(true)}} placeholder="點選或輸入商品名稱" style={{paddingLeft:36,height:50,fontSize:17}}/></div>{batchProductOpen&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden',background:'#fff',maxHeight:320,overflowY:'auto',boxShadow:'0 10px 28px rgba(15,23,42,.12)'}}>{renderProductList(batchProds,batchProductSearch,chooseBatchProduct)}</div>}{batchProduct&&<div style={{marginTop:12,padding:14,border:'2px solid var(--emerald)',borderRadius:12,background:'var(--emerald-light)'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><strong style={{fontSize:17}}>📦 {batchProduct.product.name}</strong><button onClick={()=>{setBatchProduct(null);setBatchRows([])}} style={{border:0,background:'transparent',cursor:'pointer'}}><X size={16}/></button></div><ProductSpecs item={batchProduct} onSpec={patchBatchSpec}/><div style={{fontSize:12,marginTop:8,color:'var(--text-secondary)'}}>單價：NT${itemPrice(batchProduct).toLocaleString()}　先設定好規格，再連續加入客戶。</div></div>}</div></div>
      <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>② 連續加入客戶與數量</strong><span style={{fontSize:12,color:'var(--text-muted)'}}>已加入 {batchRows.length} 位</span></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input disabled={!batchProduct} value={batchCustomerSearch} onFocus={()=>setBatchCustomerOpen(true)} onClick={()=>setBatchCustomerOpen(true)} onChange={e=>{setBatchCustomerSearch(e.target.value);setBatchCustomerOpen(true)}} placeholder={batchProduct?'姓名／手機末兩碼／Line／FB':'請先選商品'} style={{paddingLeft:36,height:50,fontSize:17}}/></div>{batchProduct&&batchCustomerOpen&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden',background:'#fff',maxHeight:300,overflowY:'auto',boxShadow:'0 10px 28px rgba(15,23,42,.12)'}}>{batchCusts.map(c=><button key={c.id} onClick={()=>addBatchCustomer(c)} style={{display:'block',width:'100%',textAlign:'left',padding:'11px 13px',border:0,borderBottom:'1px solid var(--border)',background:batchRows.some(r=>r.customer.id===c.id)?'#f8fafc':'#fff',cursor:'pointer'}}><strong>{c.name}</strong>{batchRows.some(r=>r.customer.id===c.id)&&<span className="badge badge-emerald" style={{marginLeft:8}}>已加入</span>}<div style={{fontSize:11,color:'var(--text-muted)',marginTop:2}}>{customerSecondaryLabel(c)||'無其他辨識資料'}</div></button>)}</div>}
        {batchRows.length>0&&<div style={{marginTop:12,border:'1px solid var(--border)',borderRadius:12,overflow:'hidden'}}>{batchRows.map((r,i)=><div key={r.customer.id} style={{display:'grid',gridTemplateColumns:'minmax(150px,1fr) 100px minmax(140px,1fr) 38px',gap:8,alignItems:'center',padding:'10px 12px',borderBottom:i===batchRows.length-1?0:'1px solid var(--border)',background:'#fff'}}><div><strong>{i+1}. {r.customer.name}</strong><div style={{fontSize:11,color:'var(--text-muted)'}}>{customerSecondaryLabel(r.customer)}</div></div><QuantityInput value={r.qty} min={1} onChange={v=>patchBatchRow(r.customer.id,{qty:v})} style={{width:90,height:42,fontSize:17,fontWeight:900}}/><input value={r.note} onChange={e=>patchBatchRow(r.customer.id,{note:e.target.value})} placeholder="備註"/><button onClick={()=>setBatchRows(rows=>rows.filter(x=>x.customer.id!==r.customer.id))} style={{border:0,background:'transparent',color:'var(--rose)',cursor:'pointer'}}><X size={16}/></button></div>)}</div>}
      </div></div>
      <div className="card" style={{marginBottom:14}}><div className="card-body"><label style={{display:'flex',gap:10,padding:12,border:'2px solid #fb7185',borderRadius:10,background:batchVirtual?'#fff1f2':'#fff'}}><input type="checkbox" checked={batchVirtual} onChange={e=>setBatchVirtual(e.target.checked)}/><span><strong style={{color:'#be123c'}}>⚠ 本批全部設為虛擬訂單</strong><div style={{fontSize:11,color:'var(--text-secondary)'}}>整批都不會計入實際訂貨量。</div></span></label><div className="form-group" style={{marginTop:12}}><label>本批共用備註</label><input value={batchNote} onChange={e=>setBatchNote(e.target.value)} placeholder="例如：8/24 晚班登記"/></div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:10,flexWrap:'wrap'}}><strong>共 {batchRows.length} 位客戶</strong><strong style={{fontSize:20}}>合計 NT${batchTotal.toLocaleString()}</strong></div><button className="btn btn-primary" onClick={saveBatch} disabled={saving||!batchRows.length} style={{width:'100%',justifyContent:'center',height:52,fontSize:17}}><Save size={17}/>{saving?'批次儲存中...':`一次送出 ${batchRows.length} 筆登記`}</button></div></div>
    </>}

    <div className="card"><div className="card-header"><strong><ClipboardList size={15}/> 我的最近登記</strong></div><div className="table-container"><table><thead><tr><th>客戶</th><th>商品</th><th>狀態</th></tr></thead><tbody>{entries.slice(0,20).map(e=><tr key={e.id}><td>{e.customer_name}<div style={{fontSize:10,color:'var(--text-muted)'}}>{e.customer_phone_last2?`末碼 ${e.customer_phone_last2}`:''}</div></td><td>{(e.items||[]).map((x,i)=><div key={i}>{x.product_name} ×{x.qty}</div>)}</td><td><span className={`badge ${e.status==='pending'?'badge-amber':e.status==='converted'?'badge-emerald':'badge-gray'}`}>{e.status==='pending'?'待確認':e.status==='converted'?'已轉訂單':'已取消'}</span>{e.is_virtual&&<div><span className="badge badge-rose">虛擬</span></div>}</td></tr>)}{!loading&&!entries.length&&<tr><td colSpan={3} style={{textAlign:'center',padding:24,color:'var(--text-muted)'}}>尚無登記</td></tr>}</tbody></table></div></div>
  </main></div>
}
