import { useCallback, useEffect, useMemo, useState } from 'react'
import { RefreshCw, CheckCircle, XCircle, Database, Zap } from 'lucide-react'
import { useToast } from '../components/UI'
import { HelperAPI } from '../lib/helper'
import { ProductsAPI, OrdersAPI, snapshotOrderItem } from '../lib/db'

const money=v=>`NT$${Math.round(Number(v||0)).toLocaleString()}`

export default function HelperEntries(){
 const toast=useToast();const[entries,setEntries]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[working,setWorking]=useState('')
 const load=useCallback(async()=>{setLoading(true);try{const[e,p,catalog]=await Promise.all([HelperAPI.allEntries(),ProductsAPI.list({includeArchived:true}),HelperAPI.catalog()]);setEntries(e);setProducts(p);if(catalog.length===0&&p.length>0){await HelperAPI.syncCatalog(p);toast(`已自動建立 ${p.length} 筆小幫手安全商品目錄 ✓`)}}catch(err){toast('載入失敗：'+err.message,'error')}finally{setLoading(false)}},[toast]);useEffect(()=>{load()},[load])
 const productMap=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,p])),[products]);const pending=entries.filter(e=>e.status==='pending')
 async function sync(){setWorking('sync');try{const n=await HelperAPI.syncCatalog(products);toast(`已同步 ${n} 筆小幫手安全商品目錄 ✓`)}catch(err){toast('同步失敗：'+err.message,'error')}finally{setWorking('')}}
 async function convertOne(entry){const items=(entry.items||[]).map(x=>{const p=productMap[x.product_id];if(!p||p.active===false)throw new Error(`商品「${x.product_name}」不存在或已封存`);const priceOption=(p.price_options||[]).find(o=>o.label===(x.spec?.package||''))||null;return snapshotOrderItem(p,{qty:x.qty,spec:x.spec||{},note:x.note||'',priceOption})});const order=await OrdersAPI.create({customer_id:entry.customer_id,customer_name:entry.customer_name,customer_phone_last2:entry.customer_phone_last2||'',items,total_amount:items.reduce((s,i)=>s+i.subtotal,0),note:entry.note||'',is_virtual:Boolean(entry.is_virtual),source:'helper',helper_entry_id:entry.id,created_by_uid:entry.created_by_uid||'',created_by_name:entry.created_by_name||''});await HelperAPI.updateEntry(entry.id,{status:'converted',converted_order_id:order.id,converted_at:new Date().toISOString()});return order}
 async function convert(entry){setWorking(entry.id);try{await convertOne(entry);toast(`已轉成${entry.is_virtual?'虛擬':'正式'}訂單 ✓`);await load()}catch(err){toast('轉單失敗：'+err.message,'error')}finally{setWorking('')}}
 async function convertAll(){if(!pending.length)return;if(!window.confirm(`確定要一次轉入目前 ${pending.length} 筆待確認登記？\n每筆會保留原本的正式／虛擬設定。`))return;setWorking('bulk');let ok=0;const failed=[];for(const entry of pending){try{await convertOne(entry);ok+=1}catch(err){failed.push(`${entry.customer_name||'未命名'}：${err.message}`)}}await load();setWorking('');if(!failed.length){toast(`一鍵轉單完成：${ok} 筆全部成功 ✓`);return}toast(`一鍵轉單完成：成功 ${ok} 筆、失敗 ${failed.length} 筆`,'warning');window.alert(`成功 ${ok} 筆\n失敗 ${failed.length} 筆\n\n${failed.slice(0,10).join('\n')}${failed.length>10?'\n...':''}`)}
 async function reject(entry){setWorking(entry.id);try{await HelperAPI.updateEntry(entry.id,{status:'cancelled'});toast('已取消此筆登記');await load()}catch(err){toast('取消失敗：'+err.message,'error')}finally{setWorking('')}}
 return <div className="animate-fade"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:18}}><div><h2 style={{fontSize:22,fontWeight:800}}>小幫手登記</h2><p style={{fontSize:13,color:'var(--text-secondary)',marginTop:3}}>小幫手只能登記；由正式後台確認後才寫入訂單與成本快照。</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{pending.length>0&&<button className="btn btn-primary" onClick={convertAll} disabled={Boolean(working)}><Zap size={14}/>{working==='bulk'?`轉單中...`:`一鍵全部轉單 ${pending.length}`}</button>}<button className="btn btn-ghost" onClick={sync} disabled={working==='sync'}><Database size={14}/>{working==='sync'?'同步中...':'重新同步商品目錄'}</button><button className="btn btn-ghost" onClick={load} disabled={Boolean(working)}><RefreshCw size={14}/>重新整理</button></div></div><div style={{background:'#ecfdf5',border:'1px solid #a7f3d0',padding:12,borderRadius:10,marginBottom:14,fontSize:13,color:'#065f46'}}>商品安全目錄首次會自動建立；若小幫手看不到最新商品，可按「重新同步商品目錄」。一鍵全部轉單會保留每筆原本的正式／虛擬設定。</div><div className="card"><div className="card-header"><strong>待確認 {pending.length} 筆</strong></div><div className="table-container"><table><thead><tr><th>登記人</th><th>客戶</th><th>商品明細</th><th>類型</th><th>登記金額</th><th>操作</th></tr></thead><tbody>{pending.map(e=><tr key={e.id} style={{background:e.is_virtual?'#fff1f2':undefined}}><td>{e.created_by_name||'小幫手'}</td><td><strong>{e.customer_name}</strong>{e.customer_phone_last2&&<div style={{fontSize:11,color:'var(--text-muted)'}}>末碼 {e.customer_phone_last2}</div>}</td><td>{(e.items||[]).map((x,i)=><div key={i}>{x.product_name} ×<strong>{x.qty}</strong>{x.spec?.package?`／${x.spec.package}`:''}{x.spec?.flavor?`／${x.spec.flavor}`:''}{x.spec?.color?`／${x.spec.color}`:''}{x.spec?.size?`／${x.spec.size}`:''}</div>)}{e.note&&<div style={{fontSize:11,color:'var(--text-muted)'}}>備註：{e.note}</div>}</td><td><span className={`badge ${e.is_virtual?'badge-rose':'badge-emerald'}`}>{e.is_virtual?'⚠ 虛擬':'正式'}</span></td><td>{money(e.total_amount)}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-sm btn-primary" disabled={Boolean(working)} onClick={()=>convert(e)}><CheckCircle size={12}/>{working===e.id?'轉單中...':'確認轉單'}</button><button className="btn btn-sm btn-ghost" disabled={Boolean(working)} onClick={()=>reject(e)} style={{color:'var(--rose)'}}><XCircle size={12}/>取消</button></div></td></tr>)}{!loading&&!pending.length&&<tr><td colSpan={6} style={{textAlign:'center',padding:30,color:'var(--text-muted)'}}>目前沒有待確認登記</td></tr>}</tbody></table></div></div></div>
}
