import { useCallback, useEffect, useMemo, useState } from 'react'
import { Search, X, Save, LogOut, ClipboardList } from 'lucide-react'
import { useAuth } from '../components/AuthGuard'
import { useToast } from '../components/UI'
import { HelperAPI } from '../lib/helper'
import { filterCustomers, customerSecondaryLabel, getCustomerPhoneLast2 } from '../lib/customerSearch'
import QuantityInput from '../components/QuantityInput'

function specText(item){const s=item.spec||{};return [s.package&&`組合：${s.package}`,s.flavor&&`口味：${s.flavor}`,s.color&&`顏色：${s.color}`,s.size&&`尺寸：${s.size}`].filter(Boolean).join('／')||'一般規格'}
function itemPrice(item){const opt=(item.product.price_options||[]).find(o=>o.label===item.spec?.package);return Number(opt?.price??item.product.price??0)}

export default function HelperPortal(){
  const { user,account,logout }=useAuth(); const toast=useToast()
  const[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[entries,setEntries]=useState([]),[loading,setLoading]=useState(true)
  const[customerSearch,setCustomerSearch]=useState(''),[productSearch,setProductSearch]=useState(''),[customer,setCustomer]=useState(null),[items,setItems]=useState([]),[isVirtual,setIsVirtual]=useState(false),[note,setNote]=useState(''),[saving,setSaving]=useState(false)
  const load=useCallback(async()=>{setLoading(true);try{const[c,p,e]=await Promise.all([HelperAPI.customers(),HelperAPI.catalog(),HelperAPI.myEntries(user.uid)]);setCustomers(c);setProducts(p);setEntries(e)}catch(err){toast('載入失敗：'+err.message,'error')}finally{setLoading(false)}},[user,toast])
  useEffect(()=>{if(user)load()},[user,load])
  const custs=useMemo(()=>filterCustomers(customers,customerSearch).slice(0,20),[customers,customerSearch])
  const prods=useMemo(()=>products.filter(p=>String(p.name||'').toLowerCase().includes(productSearch.toLowerCase())).slice(0,30),[products,productSearch])
  function addProduct(product){setItems(p=>[...p,{product,qty:1,spec:{package:'',flavor:'',color:'',size:''},note:''}]);setProductSearch('')}
  function patchItem(i,patch){setItems(p=>p.map((x,n)=>n===i?{...x,...patch}:x))}
  function patchSpec(i,key,value){setItems(p=>p.map((x,n)=>n===i?{...x,spec:{...x.spec,[key]:value}}:x))}
  async function save(){if(!customer){toast('請先選擇客戶','error');return}if(!items.length){toast('請至少加入一項商品','error');return}for(const x of items){if(!Number.isInteger(Number(x.qty))||Number(x.qty)<1){toast('數量至少為 1','error');return}if((x.product.price_options||[]).length&&!x.spec.package){toast(`「${x.product.name}」請選組合／包裝`,'error');return}if((x.product.spec_flavors||[]).length&&!x.spec.flavor){toast(`「${x.product.name}」請選口味`,'error');return}if(['color_size','color_free','color_only'].includes(x.product.spec_mode)&&!x.spec.color){toast(`「${x.product.name}」請選顏色`,'error');return}if(['color_size','size_only'].includes(x.product.spec_mode)&&!x.spec.size){toast(`「${x.product.name}」請選尺寸`,'error');return}}
    setSaving(true);try{const cleanItems=items.map(x=>({product_id:x.product.id,product_name:x.product.name,sale_price:itemPrice(x),qty:Number(x.qty),spec:x.spec,note:x.note||''}));await HelperAPI.createEntry({created_by_uid:user.uid,created_by_name:account?.display_name||user.email||'',customer_id:customer.id,customer_name:customer.name,customer_phone_last2:getCustomerPhoneLast2(customer),items:cleanItems,total_amount:cleanItems.reduce((s,x)=>s+x.sale_price*x.qty,0),is_virtual:isVirtual,note:note.trim()});toast('登記完成 ✓');setCustomer(null);setCustomerSearch('');setItems([]);setIsVirtual(false);setNote('');await load()}catch(err){toast('登記失敗：'+err.message,'error')}finally{setSaving(false)}}
  const total=items.reduce((s,x)=>s+itemPrice(x)*Number(x.qty||0),0)
  return <div style={{minHeight:'100vh',background:'#f8fafc'}}><header style={{position:'sticky',top:0,zIndex:20,background:'#0f172a',color:'#fff',padding:'12px 16px',display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><strong style={{fontSize:18}}>📝 小幫手團購登記</strong><div style={{fontSize:11,opacity:.6}}>{account?.display_name||user?.email}</div></div><button onClick={logout} style={{border:'1px solid rgba(255,255,255,.2)',background:'transparent',color:'#fff',borderRadius:8,padding:'8px 10px'}}><LogOut size={14}/> 登出</button></header><main style={{maxWidth:900,margin:'0 auto',padding:16}}>
    <div style={{background:'#ecfdf5',border:'1px solid #a7f3d0',padding:'10px 12px',borderRadius:10,marginBottom:14,fontSize:13,color:'#065f46'}}>此頁只提供客戶查詢與訂單登記；成本、供應商、毛利、財務與付款資料不會提供給小幫手。</div>
    <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>① 選擇客戶</strong></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="姓名／手機末兩碼／Line／FB" style={{paddingLeft:36,height:48,fontSize:16}}/></div>{customerSearch&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden'}}>{custs.map(c=><button key={c.id} onClick={()=>{setCustomer(c);setCustomerSearch('')}} style={{display:'block',width:'100%',textAlign:'left',padding:'10px 12px',border:0,borderBottom:'1px solid var(--border)',background:'#fff'}}><strong>{c.name}</strong><div style={{fontSize:11,color:'var(--text-muted)'}}>{customerSecondaryLabel(c)||'無其他辨識資料'}</div></button>)}</div>}{customer&&<div style={{marginTop:10,padding:12,borderRadius:10,background:'var(--indigo-light)',display:'flex',justifyContent:'space-between'}}><strong>👤 {customer.name}{getCustomerPhoneLast2(customer)?`（末碼 ${getCustomerPhoneLast2(customer)}）`:''}</strong><button onClick={()=>setCustomer(null)} style={{border:0,background:'transparent'}}><X size={16}/></button></div>}</div></div>
    <div className="card" style={{marginBottom:14}}><div className="card-header"><strong>② 加入商品</strong></div><div className="card-body"><div className="search-input-wrap"><Search size={16}/><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="輸入商品名稱" style={{paddingLeft:36,height:48,fontSize:16}}/></div>{productSearch&&<div style={{marginTop:8,border:'1px solid var(--border)',borderRadius:10,overflow:'hidden'}}>{prods.map(p=><button key={p.id} onClick={()=>addProduct(p)} style={{display:'flex',width:'100%',justifyContent:'space-between',padding:'10px 12px',border:0,borderBottom:'1px solid var(--border)',background:'#fff'}}><span>{p.name}</span><strong>NT${Number(p.price||0).toLocaleString()}</strong></button>)}</div>}{items.map((x,i)=><div key={i} style={{marginTop:10,padding:12,border:'1px solid var(--border)',borderRadius:10,background:'#fff'}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong style={{flex:1}}>{x.product.name}</strong><QuantityInput value={x.qty} min={1} onChange={v=>patchItem(i,{qty:v})} style={{width:90,height:44,fontSize:18,fontWeight:900}}/><button onClick={()=>setItems(p=>p.filter((_,n)=>n!==i))} style={{border:0,background:'transparent',color:'var(--rose)'}}><X size={16}/></button></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:8}}>{(x.product.price_options||[]).length>0&&<select value={x.spec.package} onChange={e=>patchSpec(i,'package',e.target.value)}><option value="">選組合／包裝 *</option>{x.product.price_options.map(o=><option key={o.label} value={o.label}>{o.label}｜NT${Number(o.price||0).toLocaleString()}</option>)}</select>}{(x.product.spec_flavors||[]).length>0&&<select value={x.spec.flavor} onChange={e=>patchSpec(i,'flavor',e.target.value)}><option value="">選口味 *</option>{x.product.spec_flavors.map(v=><option key={v}>{v}</option>)}</select>}{['color_size','color_free','color_only'].includes(x.product.spec_mode)&&<select value={x.spec.color} onChange={e=>patchSpec(i,'color',e.target.value)}><option value="">選顏色 *</option>{(x.product.spec_colors||[]).map(v=><option key={v}>{v}</option>)}</select>}{['color_size','size_only'].includes(x.product.spec_mode)&&<select value={x.spec.size} onChange={e=>patchSpec(i,'size',e.target.value)}><option value="">選尺寸 *</option>{(x.product.spec_sizes||[]).map(v=><option key={v}>{v}</option>)}</select>}<input value={x.note} onChange={e=>patchItem(i,{note:e.target.value})} placeholder="備註" style={{maxWidth:180}}/></div><div style={{marginTop:7,fontSize:12,color:'var(--text-secondary)'}}>{specText(x)}　小計 NT${(itemPrice(x)*Number(x.qty||0)).toLocaleString()}</div></div>)}</div></div>
    <div className="card" style={{marginBottom:14}}><div className="card-body"><label style={{display:'flex',gap:10,padding:12,border:'2px solid #fb7185',borderRadius:10,background:isVirtual?'#fff1f2':'#fff'}}><input type="checkbox" checked={isVirtual} onChange={e=>setIsVirtual(e.target.checked)}/><span><strong style={{color:'#be123c'}}>⚠ 虛擬訂單</strong><div style={{fontSize:11,color:'var(--text-secondary)'}}>客戶尚未完全確定時勾選；不會計入實際訂貨量。</div></span></label><div className="form-group" style={{marginTop:12}}><label>備註</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：客戶晚點確認"/></div><div style={{textAlign:'right',fontSize:20,fontWeight:900,marginBottom:10}}>合計 NT${total.toLocaleString()}</div><button className="btn btn-primary" onClick={save} disabled={saving} style={{width:'100%',justifyContent:'center',height:50,fontSize:16}}><Save size={16}/>{saving?'儲存中...':'送出登記'}</button></div></div>
    <div className="card"><div className="card-header"><strong><ClipboardList size={15}/> 我的最近登記</strong></div><div className="table-container"><table><thead><tr><th>客戶</th><th>商品</th><th>狀態</th></tr></thead><tbody>{entries.slice(0,20).map(e=><tr key={e.id}><td>{e.customer_name}<div style={{fontSize:10,color:'var(--text-muted)'}}>{e.customer_phone_last2?`末碼 ${e.customer_phone_last2}`:''}</div></td><td>{(e.items||[]).map((x,i)=><div key={i}>{x.product_name} ×{x.qty}</div>)}</td><td><span className={`badge ${e.status==='pending'?'badge-amber':e.status==='converted'?'badge-emerald':'badge-gray'}`}>{e.status==='pending'?'待確認':e.status==='converted'?'已轉訂單':'已取消'}</span>{e.is_virtual&&<div><span className="badge badge-rose">虛擬</span></div>}</td></tr>)}{!loading&&!entries.length&&<tr><td colSpan={3} style={{textAlign:'center',padding:24,color:'var(--text-muted)'}}>尚無登記</td></tr>}</tbody></table></div></div>
  </main></div>
}
