import { useState, useEffect, useCallback, useRef } from 'react'
import { OrdersAPI, ProductsAPI, CustomersAPI, effectiveOrderAmount, orderSnapshotCost } from '../lib/db'
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { TrendingUp, DollarSign, Package, Search, Printer, ChevronDown, Download, WalletCards, ReceiptText, Building2 } from 'lucide-react'

const CAT_COLORS = { daily:'#3b82f6',frozen:'#06b6d4',clothing:'#ec4899',biscuit:'#f59e0b',candy:'#8b5cf6',other:'#6b7280' }
const CAT_LABELS = { daily:'日用品',frozen:'冷凍食品',clothing:'服飾',biscuit:'餅乾',candy:'糖果',other:'其他' }
const money = n => `NT$${Math.round(Number(n || 0)).toLocaleString()}`
const dateText = d => d ? new Date(d).toLocaleDateString('zh-TW') : '—'

function downloadBlob(filename,content,type) {
  const blob = new Blob([content],{ type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href=url; a.download=filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url)
}
function escapeCsv(v) { return `"${String(v ?? '').replaceAll('"','""')}"` }
function exportCsv(orders,filename='group-buy-report.csv') {
  const rows = [['訂單日期','客戶','商品','規格/口味','數量','售價','成本','訂單狀態','收款狀態','退款','訂單有效金額']]
  orders.forEach(o => (o.items || []).forEach(item => { const s=item.spec || {}; rows.push([dateText(o.order_date),o.customer_name,item.product_name || item.name,[s.flavor && `口味:${s.flavor}`,s.color,s.size].filter(Boolean).join('/'),item.qty,item.sale_price ?? item.price ?? 0,item.cost_price ?? '',o.status,o.payment_status,o.refund_amount || 0,effectiveOrderAmount(o)]) }))
  downloadBlob(filename,'\ufeff'+rows.map(r => r.map(escapeCsv).join(',')).join('\n'),'text/csv;charset=utf-8')
}
function exportExcel(orders,filename='group-buy-report.xls') {
  const body = orders.flatMap(o => (o.items || []).map(item => { const s=item.spec || {}; return `<tr><td>${dateText(o.order_date)}</td><td>${o.customer_name || ''}</td><td>${item.product_name || item.name || ''}</td><td>${[s.flavor && `口味:${s.flavor}`,s.color,s.size].filter(Boolean).join('/')}</td><td>${item.qty || 0}</td><td>${item.sale_price ?? item.price ?? 0}</td><td>${item.cost_price ?? ''}</td><td>${o.status || ''}</td><td>${o.payment_status || ''}</td><td>${o.refund_amount || 0}</td><td>${effectiveOrderAmount(o)}</td></tr>` })).join('')
  const html = `\ufeff<html><head><meta charset="utf-8"></head><body><table border="1"><tr><th>訂單日期</th><th>客戶</th><th>商品</th><th>規格/口味</th><th>數量</th><th>售價</th><th>成本</th><th>訂單狀態</th><th>收款狀態</th><th>退款</th><th>訂單有效金額</th></tr>${body}</table></body></html>`
  downloadBlob(filename,html,'application/vnd.ms-excel;charset=utf-8')
}
function specLabel(item) { const s=item?.spec || {}; const parts=[]; if(s.flavor) parts.push(`口味:${s.flavor}`); if(s.color) parts.push(s.color); if(s.size) parts.push(s.size); return parts.length ? `（${parts.join('／')}）` : '' }
function periodBounds(filterMode,inputMonth,inputStart,inputEnd) {
  if (filterMode === 'month' && inputMonth) { const [y,m] = inputMonth.split('-').map(Number); return [new Date(y,m-1,1,0,0,0).toISOString(),new Date(y,m,0,23,59,59,999).toISOString()] }
  if (filterMode === 'range' && inputStart && inputEnd) return [new Date(inputStart+'T00:00:00').toISOString(),new Date(inputEnd+'T23:59:59').toISOString()]
  return [null,null]
}

export default function Reports() {
  const currentMonth = (() => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}` })()
  const [orders,setOrders] = useState([]); const [products,setProducts] = useState([]); const [customers,setCustomers] = useState([]); const [loading,setLoading] = useState(true); const [error,setError] = useState('')
  const [filterMode,setFilterMode] = useState('month'); const [inputMonth,setInputMonth] = useState(currentMonth); const [inputStart,setInputStart] = useState(''); const [inputEnd,setInputEnd] = useState('')
  const [activeTab,setActiveTab] = useState('summary'); const [buyerSearch,setBuyerSearch] = useState(''); const [buyerStatusFilter,setBuyerStatusFilter] = useState('all'); const [buyerPayFilter,setBuyerPayFilter] = useState('all'); const [buyerProdFilter,setBuyerProdFilter] = useState('')
  const [prodDropOpen,setProdDropOpen] = useState(false); const [prodDropSearch,setProdDropSearch] = useState(''); const prodDropRef = useRef(null); const [trackProd,setTrackProd] = useState(null); const [prodSearch,setProdSearch] = useState('')

  useEffect(() => { const h=e => { if(prodDropRef.current && !prodDropRef.current.contains(e.target)) setProdDropOpen(false) }; document.addEventListener('mousedown',h); return () => document.removeEventListener('mousedown',h) },[])
  const loadMaster = useCallback(async () => { try { const [prods,custs] = await Promise.all([ProductsAPI.list({ includeArchived:true }),CustomersAPI.list({ includeArchived:true })]); setProducts(prods); setCustomers(custs) } catch (err) { setError('主檔載入失敗：'+err.message) } },[])
  const loadOrders = useCallback(async () => { setLoading(true); setError(''); try { const [start,end] = periodBounds(filterMode,inputMonth,inputStart,inputEnd); const rows = start && end ? await OrdersAPI.listByDateRange(start,end) : await OrdersAPI.list(); setOrders(rows) } catch (err) { setError('訂單報表載入失敗：'+err.message) } finally { setLoading(false) } },[filterMode,inputMonth,inputStart,inputEnd])
  useEffect(() => { loadMaster() },[loadMaster]); useEffect(() => { if(filterMode === 'range' && (!inputStart || !inputEnd)) return; loadOrders() },[loadOrders,filterMode,inputStart,inputEnd])

  const currentCostMap = Object.fromEntries(products.map(p => [p.id,Number(p.cost || 0)])); const currentCatMap = Object.fromEntries(products.map(p => [p.id,p.category || 'other'])
  const validOrders = orders.filter(o => o.status !== 'cancelled'); const shippedOrders = validOrders.filter(o => o.status === 'shipped'); const cancelledOrders = orders.filter(o => o.status === 'cancelled')
  const orderValue = validOrders.reduce((s,o) => s+effectiveOrderAmount(o),0); const shippedRevenue = shippedOrders.reduce((s,o) => s+effectiveOrderAmount(o),0); const shippedCost = shippedOrders.reduce((s,o) => s+orderSnapshotCost(o,currentCostMap),0); const shippedProfit = shippedRevenue-shippedCost
  const collectedAmount = validOrders.filter(o => ['paid','partial_refund','refunded'].includes(o.payment_status)).reduce((s,o) => s+effectiveOrderAmount(o),0); const outstandingAmount = validOrders.filter(o => o.payment_status === 'unpaid').reduce((s,o) => s+effectiveOrderAmount(o),0)
  const refundAmount = validOrders.reduce((s,o) => s+Number(o.refund_amount || 0),0); const cancelledAmount = cancelledOrders.reduce((s,o) => s+Number(o.total_amount || 0),0); const supplierPaidCost = validOrders.filter(o => o.payable_status === 'paid').reduce((s,o) => s+orderSnapshotCost(o,currentCostMap),0); const payableOutstanding = validOrders.filter(o => o.payable_status !== 'paid').reduce((s,o) => s+orderSnapshotCost(o,currentCostMap),0); const netCashFlow = collectedAmount-supplierPaidCost

  const trendMap = {}; shippedOrders.forEach(o => { const d=new Date(o.order_date); const key=filterMode === 'all' ? `${d.getFullYear()}/${d.getMonth()+1}月` : `${d.getMonth()+1}/${d.getDate()}`; trendMap[key]=(trendMap[key] || 0)+effectiveOrderAmount(o) }); const trendData = Object.entries(trendMap).map(([date,amount]) => ({ date,amount }))
  const prodSales = {}; validOrders.forEach(o => (o.items || []).forEach(item => { const key=item.product_id || item.id || item.product_name || item.name; if(!prodSales[key]) prodSales[key]={ name:item.product_name || item.name,qty:0,revenue:0 }; prodSales[key].qty+=Number(item.qty || 0); prodSales[key].revenue+=Number(item.sale_price ?? item.price ?? 0)*Number(item.qty || 0) })); const topProds = Object.values(prodSales).sort((a,b) => b.qty-a.qty).slice(0,8).map(x => ({ ...x,chartName:x.name.length>12 ? x.name.slice(0,12)+'…' : x.name }))
  const catSales = {}; validOrders.forEach(o => (o.items || []).forEach(item => { const cat=item.category || currentCatMap[item.product_id || item.id] || 'other'; catSales[cat]=(catSales[cat] || 0)+Number(item.sale_price ?? item.price ?? 0)*Number(item.qty || 0) })); const catData = Object.entries(catSales).map(([cat,value]) => ({ name:CAT_LABELS[cat] || cat,value,color:CAT_COLORS[cat] || '#999' }))

  const trackBuyers = trackProd ? (() => { const map={}; validOrders.forEach(o => { const matches=(o.items || []).filter(i => (i.product_id || i.id) === trackProd.id || (i.product_name || i.name) === trackProd.name); if(!matches.length) return; if(!map[o.customer_name]) map[o.customer_name]={ qty:0,pending:0,total:0 }; matches.forEach(found => { const qty=Number(found.qty || 0); map[o.customer_name].qty+=qty; if(o.status === 'pending') map[o.customer_name].pending+=qty; map[o.customer_name].total+=Number(found.sale_price ?? found.price ?? 0)*qty }) }); return Object.entries(map).sort((a,b) => b[1].qty-a[1].qty).map(([name,data]) => ({ name,...data })) })() : []
  const custMap = Object.fromEntries(customers.map(c => [c.id,c])); const buyerRows = (() => { const map={}; validOrders.forEach(o => { const cid=o.customer_id || o.customer_name; if(!map[cid]) map[cid]={ id:cid,name:o.customer_name,line_nick:custMap[o.customer_id]?.line_nick || '',fb_name:custMap[o.customer_id]?.fb_name || '',orders:[] }; map[cid].orders.push(o) }); return Object.values(map).map(c => { const os=c.orders; return { ...c,totalAmt:os.reduce((s,o) => s+effectiveOrderAmount(o),0),pendingCnt:os.filter(o => o.status === 'pending').length,shippedCnt:os.filter(o => o.status === 'shipped').length,unpaidCnt:os.filter(o => o.payment_status === 'unpaid').length,paidCnt:os.filter(o => ['paid','partial_refund','refunded'].includes(o.payment_status)).length } }) })()
  const selectedProd = products.find(p => p.id === buyerProdFilter); const filtBuyers = buyerRows.filter(c => { const q=buyerSearch.toLowerCase(); const mName=!q || c.name.toLowerCase().includes(q) || c.line_nick.toLowerCase().includes(q) || c.fb_name.toLowerCase().includes(q); const mStatus=buyerStatusFilter === 'all' || (buyerStatusFilter === 'pending' ? c.pendingCnt>0 : c.shippedCnt>0); const mPay=buyerPayFilter === 'all' || (buyerPayFilter === 'unpaid' ? c.unpaidCnt>0 : c.paidCnt>0); const mProd=!buyerProdFilter || c.orders.some(o => (o.items || []).some(i => (i.product_id || i.id) === buyerProdFilter)); return mName && mStatus && mPay && mProd })
  function getBuyerOrders(buyer) { return buyer.orders.filter(o => { const mStatus=buyerStatusFilter === 'all' || o.status === buyerStatusFilter; const mPay=buyerPayFilter === 'all' || (buyerPayFilter === 'unpaid' ? o.payment_status === 'unpaid' : ['paid','partial_refund','refunded'].includes(o.payment_status)); const mProd=!buyerProdFilter || (o.items || []).some(i => (i.product_id || i.id) === buyerProdFilter); return mStatus && mPay && mProd }) }

  const supplierMap = {}; validOrders.forEach(o => (o.items || []).forEach(item => { const name=item.supplier || '未指定供應商'; if(!supplierMap[name]) supplierMap[name]={ supplier:name,total:0,paid:0,outstanding:0 }; const cost=Number(item.cost_price ?? currentCostMap[item.product_id || item.id] ?? 0)*Number(item.qty || 0); supplierMap[name].total+=cost; if(o.payable_status === 'paid') supplierMap[name].paid+=cost; else supplierMap[name].outstanding+=cost })); const supplierRows = Object.values(supplierMap).sort((a,b) => b.outstanding-a.outstanding)
  const monthlyMap = {}; shippedOrders.forEach(o => { const d=new Date(o.order_date); const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; if(!monthlyMap[key]) monthlyMap[key]={ month:key,revenue:0,cost:0,profit:0 }; monthlyMap[key].revenue+=effectiveOrderAmount(o); monthlyMap[key].cost+=orderSnapshotCost(o,currentCostMap) }); const monthlyRows = Object.values(monthlyMap).sort((a,b) => a.month.localeCompare(b.month)).map(r => ({ ...r,profit:r.revenue-r.cost }))
  const filtProds = products.filter(p => p.active !== false && p.name.toLowerCase().includes(prodSearch.toLowerCase())); const filtProdsDrop = products.filter(p => p.name.toLowerCase().includes(prodDropSearch.toLowerCase())); const periodLabel = filterMode === 'all' ? '全部期間' : filterMode === 'month' ? inputMonth : `${inputStart || '?'} ~ ${inputEnd || '?'}`

  return <div className="animate-fade">
    <div style={{ display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20,flexWrap:'wrap',gap:12 }}><div><h2 style={{ fontSize:22,fontWeight:800 }}>銷售與財務報表</h2><p style={{ color:'var(--text-secondary)',fontSize:13,marginTop:2 }}>取消單排除、退款扣除、成本採下單當時快照；預設只讀取本月資料</p></div><div style={{ display:'flex',gap:7,flexWrap:'wrap' }}><button className="btn btn-ghost" onClick={() => exportCsv(validOrders,`group-buy-${periodLabel}.csv`)}><Download size={13}/>CSV</button><button className="btn btn-ghost" onClick={() => exportExcel(validOrders,`group-buy-${periodLabel}.xls`)}><Download size={13}/>Excel</button><button className="btn btn-ghost" onClick={() => window.print()}><Printer size={14}/>列印</button></div></div>
    <div style={{ background:'var(--surface)',borderRadius:'var(--radius)',padding:'14px 16px',marginBottom:18,display:'flex',gap:12,flexWrap:'wrap',alignItems:'center',boxShadow:'var(--shadow-sm)' }}><div style={{ display:'flex',gap:6 }}>{[['month','本月/指定月份'],['range','自訂區間'],['all','全部歷史']].map(([v,l]) => <button key={v} className={`btn btn-sm ${filterMode === v ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setFilterMode(v)}>{l}</button>)}</div>{filterMode === 'month' && <input type="month" value={inputMonth} onChange={e => setInputMonth(e.target.value)}/>} {filterMode === 'range' && <><input type="date" value={inputStart} onChange={e => setInputStart(e.target.value)}/><span>〜</span><input type="date" value={inputEnd} onChange={e => setInputEnd(e.target.value)}/></>}<span style={{ marginLeft:'auto',color:'var(--text-muted)',fontSize:12 }}>{loading ? '讀取中...' : `${orders.length} 筆訂單`}</span></div>
    {error && <div style={{ background:'var(--rose-light)',color:'var(--rose)',padding:12,borderRadius:8,marginBottom:14 }}>{error}</div>}
    <div style={{ display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,marginBottom:18 }}>{[
      { label:'有效訂單總額',value:money(orderValue),icon:ReceiptText,bg:'linear-gradient(135deg,#6366f1,#4338ca)' },{ label:'已出貨營收',value:money(shippedRevenue),icon:DollarSign,bg:'linear-gradient(135deg,#10b981,#059669)' },{ label:'已收款淨額',value:money(collectedAmount),icon:WalletCards,bg:'linear-gradient(135deg,#0ea5e9,#0284c7)' },{ label:'未收款',value:money(outstandingAmount),icon:ReceiptText,bg:'linear-gradient(135deg,#f59e0b,#d97706)' },{ label:'已出貨毛利',value:money(shippedProfit),icon:TrendingUp,bg:'linear-gradient(135deg,#14b8a6,#0f766e)' },{ label:'退款',value:money(refundAmount),icon:Package,bg:'linear-gradient(135deg,#f43f5e,#be123c)' },
    ].map(s => <div key={s.label} className="stat-card" style={{ background:s.bg }}><div style={{ fontSize:11,fontWeight:700,opacity:.8,marginBottom:6 }}>{s.label}</div><div style={{ fontSize:21,fontWeight:900 }}>{loading ? '—' : s.value}</div><s.icon size={27} style={{ position:'absolute',right:14,top:'50%',transform:'translateY(-50%)',opacity:.22 }}/></div>)}</div>
    <div style={{ background:'var(--surface-2)',borderRadius:10,padding:'9px 12px',marginBottom:18,fontSize:12,color:'var(--text-secondary)' }}>定義：<strong>有效訂單總額</strong>＝未取消訂單金額－退款；<strong>已出貨營收</strong>＝已出貨有效金額；<strong>毛利</strong>＝已出貨營收－下單時成本快照。取消金額 {money(cancelledAmount)} 不計入上述數字。</div>
    <div className="tabs" style={{ marginBottom:18 }}><button className={`tab ${activeTab === 'summary' ? 'active' : ''}`} onClick={() => setActiveTab('summary')}>📊 銷售分析</button><button className={`tab ${activeTab === 'buyer' ? 'active' : ''}`} onClick={() => setActiveTab('buyer')}>👥 買家查詢</button><button className={`tab ${activeTab === 'finance' ? 'active' : ''}`} onClick={() => setActiveTab('finance')}>💰 財務 / 損益</button></div>

    {activeTab === 'summary' && <>
      <div style={{ display:'grid',gridTemplateColumns:'2fr 1fr',gap:14,marginBottom:18 }}><div className="card"><div className="card-header" style={{ fontWeight:700 }}>📈 已出貨營收趨勢</div><div style={{ padding:'16px 8px' }}>{!trendData.length ? <div className="empty-state">此期間無已出貨資料</div> : <ResponsiveContainer width="100%" height={220}><LineChart data={trendData}><XAxis dataKey="date" tick={{ fontSize:11 }}/><YAxis tick={{ fontSize:11 }}/><Tooltip formatter={v => [money(v),'已出貨營收']}/><Line type="monotone" dataKey="amount" stroke="#6366f1" strokeWidth={2.5}/></LineChart></ResponsiveContainer>}</div></div><div className="card"><div className="card-header" style={{ fontWeight:700 }}>🏷️ 有效訂單分類佔比</div><div style={{ padding:'16px 8px' }}>{!catData.length ? <div className="empty-state">無資料</div> : <ResponsiveContainer width="100%" height={220}><PieChart><Pie data={catData} cx="50%" cy="50%" outerRadius={76} dataKey="value" label={({name,percent}) => `${name} ${Math.round(percent*100)}%`} labelLine={false} fontSize={10}>{catData.map((e,i) => <Cell key={i} fill={e.color}/>)}</Pie><Tooltip formatter={v => [money(v)]}/></PieChart></ResponsiveContainer>}</div></div></div>
      <div className="card" style={{ marginBottom:18 }}><div className="card-header" style={{ fontWeight:700 }}>🏆 熱銷商品 Top 8（同商品不同規格/口味會全部加總）</div><div style={{ padding:'16px 8px' }}>{!topProds.length ? <div className="empty-state">無資料</div> : <ResponsiveContainer width="100%" height={230}><BarChart data={topProds} layout="vertical"><XAxis type="number" tick={{ fontSize:11 }}/><YAxis dataKey="chartName" type="category" width={115} tick={{ fontSize:11 }}/><Tooltip formatter={v => [`${v} 件`,'數量']}/><Bar dataKey="qty" fill="#6366f1"/></BarChart></ResponsiveContainer>}</div></div>
      <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:14 }}><div className="card"><div className="card-header" style={{ fontWeight:700 }}>🔍 商品買家追蹤</div><div className="card-body"><div className="search-input-wrap" style={{ marginBottom:10 }}><Search size={14}/><input value={prodSearch} onChange={e => setProdSearch(e.target.value)} placeholder="搜尋商品..." style={{ padding:'8px 8px 8px 32px',width:'100%' }}/></div><div style={{ maxHeight:300,overflowY:'auto' }}>{filtProds.map(p => <div key={p.id} onClick={() => setTrackProd(p)} style={{ padding:'8px 10px',cursor:'pointer',borderRadius:8,background:trackProd?.id === p.id ? 'var(--indigo-light)' : 'transparent',fontWeight:trackProd?.id === p.id ? 700 : 400 }}>{p.name}</div>)}</div></div></div><div className="card"><div className="card-header" style={{ fontWeight:700 }}>{trackProd ? `${trackProd.name} — 買家名單` : '請選商品'}</div><div className="table-container"><table><thead><tr><th>客戶</th><th>總數</th><th>未出</th><th>金額</th></tr></thead><tbody>{trackBuyers.map(b => <tr key={b.name}><td>{b.name}</td><td>{b.qty}</td><td>{b.pending || '—'}</td><td>{money(b.total)}</td></tr>)}</tbody></table></div></div></div>
    </>}

    {activeTab === 'buyer' && <><div style={{ background:'var(--surface)',borderRadius:'var(--radius)',padding:14,marginBottom:14,display:'flex',gap:8,flexWrap:'wrap',alignItems:'center' }}><div className="search-input-wrap" style={{ flex:1,minWidth:170 }}><Search size={14}/><input value={buyerSearch} onChange={e => setBuyerSearch(e.target.value)} placeholder="姓名、Line、FB..." style={{ padding:'7px 7px 7px 30px',width:'100%' }}/></div>{['all','pending','shipped'].map(v => <button key={v} className={`btn btn-sm ${buyerStatusFilter === v ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setBuyerStatusFilter(v)}>{v === 'all' ? '出貨：全部' : v === 'pending' ? '未出貨' : '已出貨'}</button>)}{['all','unpaid','paid'].map(v => <button key={v} className={`btn btn-sm ${buyerPayFilter === v ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setBuyerPayFilter(v)}>{v === 'all' ? '收款：全部' : v === 'unpaid' ? '未收款' : '已收款/退款後'}</button>)}<div className="dropdown" ref={prodDropRef} style={{ minWidth:170 }}><button className="btn btn-ghost btn-sm" onClick={() => setProdDropOpen(v => !v)}>{selectedProd?.name || '商品：全部'}<ChevronDown size={12}/></button>{prodDropOpen && <div className="dropdown-menu" style={{ width:230 }}><div style={{ padding:7 }}><input autoFocus value={prodDropSearch} onChange={e => setProdDropSearch(e.target.value)} placeholder="搜尋商品"/></div><div className="dropdown-item" onClick={() => { setBuyerProdFilter(''); setProdDropOpen(false) }}>全部商品</div>{filtProdsDrop.slice(0,40).map(p => <div key={p.id} className="dropdown-item" onClick={() => { setBuyerProdFilter(p.id); setProdDropOpen(false) }}>{p.name}</div>)}</div>}</div></div><div className="card"><div className="table-container"><table><thead><tr><th>客戶</th><th>聯絡辨識</th><th>訂單</th><th>有效金額</th><th>明細</th></tr></thead><tbody>{filtBuyers.map(b => { const bos=getBuyerOrders(b); return <tr key={b.id}><td style={{ fontWeight:800 }}>{b.name}</td><td style={{ fontSize:12,color:'var(--text-secondary)' }}>{b.line_nick && `Line: ${b.line_nick}`} {b.fb_name && `FB: ${b.fb_name}`}</td><td>{bos.length} 筆</td><td style={{ fontWeight:800,color:'var(--indigo)' }}>{money(bos.reduce((s,o) => s+effectiveOrderAmount(o),0))}</td><td style={{ fontSize:12 }}>{bos.flatMap(o => (o.items || []).map((item,i) => <div key={`${o.id}-${i}`}>{item.product_name || item.name}{specLabel(item)} ×{item.qty}</div>))}</td></tr> })}</tbody></table></div></div></>}

    {activeTab === 'finance' && <><div style={{ display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginBottom:16 }}>{[['應收帳款（未收款）',outstandingAmount,WalletCards,'var(--rose-light)','var(--rose)'],['應付帳款（供應商未付款）',payableOutstanding,Building2,'var(--amber-light)','#b45309'],['已付供應商成本',supplierPaidCost,Building2,'var(--emerald-light)','var(--emerald)'],['現金流淨額',netCashFlow,DollarSign,'var(--sky-light)','#0369a1']].map(([label,value,Icon,bg,color]) => <div key={label} style={{ background:bg,borderRadius:10,padding:14,position:'relative' }}><div style={{ fontSize:11,color,fontWeight:700 }}>{label}</div><div style={{ fontSize:20,color,fontWeight:900,marginTop:5 }}>{money(value)}</div><Icon size={24} style={{ position:'absolute',right:12,top:16,color,opacity:.35 }}/></div>)}</div><div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginBottom:16 }}><div className="card"><div className="card-header" style={{ fontWeight:700 }}>🏭 供應商應付帳款</div><div className="table-container"><table><thead><tr><th>供應商</th><th>總成本</th><th>已付</th><th>未付</th></tr></thead><tbody>{supplierRows.map(r => <tr key={r.supplier}><td>{r.supplier}</td><td>{money(r.total)}</td><td>{money(r.paid)}</td><td style={{ fontWeight:800,color:r.outstanding ? 'var(--rose)' : 'var(--emerald)' }}>{money(r.outstanding)}</td></tr>)}</tbody></table></div></div><div className="card"><div className="card-header" style={{ fontWeight:700 }}>📆 月損益（已出貨）</div><div className="table-container"><table><thead><tr><th>月份</th><th>營收</th><th>成本</th><th>毛利</th></tr></thead><tbody>{monthlyRows.map(r => <tr key={r.month}><td>{r.month}</td><td>{money(r.revenue)}</td><td>{money(r.cost)}</td><td style={{ fontWeight:800,color:r.profit>=0 ? 'var(--emerald)' : 'var(--rose)' }}>{money(r.profit)}</td></tr>)}</tbody></table></div></div></div><div style={{ background:'var(--surface-2)',borderRadius:10,padding:12,fontSize:12,color:'var(--text-secondary)' }}>現金流淨額＝已收款淨額（退款後）－已標記「供應商已付款」的歷史成本。供應商資料來自商品下單當時的快照；若舊訂單沒有快照，才會回退使用目前商品成本。</div></>}
  </div>
}
