import { useState, useEffect, useCallback, useMemo } from 'react'
import { OrdersAPI, ProductsAPI, effectiveOrderAmount, orderSnapshotCost } from '../lib/db'
import { ExpensesAPI, expenseSignedAmount, EXPENSE_TYPES } from '../lib/expenses'
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { TrendingUp, DollarSign, Package, Search, Printer, Download, WalletCards, ReceiptText, Truck } from 'lucide-react'

const CAT_COLORS = { daily:'#3b82f6', frozen:'#06b6d4', clothing:'#ec4899', biscuit:'#f59e0b', candy:'#8b5cf6', other:'#6b7280' }
const CAT_LABELS = { daily:'日用品', frozen:'冷凍食品', clothing:'服飾', biscuit:'餅乾', candy:'糖果', other:'其他' }
const money = value => `NT$${Math.round(Number(value || 0)).toLocaleString()}`
const signedMoney = value => `${Number(value || 0) >= 0 ? '+' : '-'}NT$${Math.round(Math.abs(Number(value || 0))).toLocaleString()}`
const dateText = value => value ? new Date(value).toLocaleDateString('zh-TW') : '—'
const monthKey = value => { const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}` }

function specText(item) { const spec=item?.spec||{}; return [spec.package&&`組合:${spec.package}`,spec.flavor&&`口味:${spec.flavor}`,spec.color,spec.size].filter(Boolean).join(' / ') }
function periodBounds(mode,month,start,end){if(mode==='month'&&month){const[y,m]=month.split('-').map(Number);return[new Date(y,m-1,1).toISOString(),new Date(y,m,0,23,59,59,999).toISOString()]}if(mode==='range'&&start&&end)return[new Date(`${start}T00:00:00`).toISOString(),new Date(`${end}T23:59:59`).toISOString()];return[null,null]}
function expenseInPeriod(row,mode,month,start,end){if(mode==='all')return true;if(mode==='month')return row.month===month;if(mode==='range'){if(!start||!end)return false;const first=`${row.month}-01`;const[y,m]=row.month.split('-').map(Number);const last=`${row.month}-${String(new Date(y,m,0).getDate()).padStart(2,'0')}`;return last>=start&&first<=end}return false}
function downloadBlob(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function escapeCsv(value){return `"${String(value??'').replaceAll('"','""')}"`}
function exportCsv(orders,expenses,filename){const rows=[['類別','日期/月','客戶/廠商','商品/費用類型','規格/備註','數量','收入','成本/費用']];orders.forEach(o=>(o.items||[]).forEach(i=>rows.push(['訂單',dateText(o.order_date),o.customer_name,i.product_name||i.name,specText(i),i.qty,Number(i.sale_price??i.price??0)*Number(i.qty||0),Number(i.cost_price||0)*Number(i.qty||0)])));expenses.forEach(r=>rows.push(['其他費用',r.month,r.supplier,EXPENSE_TYPES.find(t=>t.id===r.type)?.label||r.type,r.note||'',1,'',expenseSignedAmount(r)]));downloadBlob(filename,'\ufeff'+rows.map(r=>r.map(escapeCsv).join(',')).join('\n'),'text/csv;charset=utf-8')}

export default function Reports(){
  const currentMonth=useMemo(()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`},[])
  const[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[expenses,setExpenses]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const[filterMode,setFilterMode]=useState('month'),[inputMonth,setInputMonth]=useState(currentMonth),[inputStart,setInputStart]=useState(''),[inputEnd,setInputEnd]=useState(''),[activeTab,setActiveTab]=useState('summary'),[trackProd,setTrackProd]=useState(null),[prodSearch,setProdSearch]=useState('')
  const loadBase=useCallback(async()=>{try{const[p,e]=await Promise.all([ProductsAPI.list({includeArchived:true}),ExpensesAPI.list()]);setProducts(p);setExpenses(e)}catch(err){setError(`報表基礎資料載入失敗：${err.message}`)}},[])
  const loadOrders=useCallback(async()=>{if(filterMode==='range'&&(!inputStart||!inputEnd))return;setLoading(true);setError('');try{const[start,end]=periodBounds(filterMode,inputMonth,inputStart,inputEnd);setOrders(start&&end?await OrdersAPI.listByDateRange(start,end):await OrdersAPI.list())}catch(err){setError(`訂單報表載入失敗：${err.message}`)}finally{setLoading(false)}},[filterMode,inputMonth,inputStart,inputEnd])
  useEffect(()=>{loadBase()},[loadBase]);useEffect(()=>{loadOrders()},[loadOrders])

  const periodExpenses=expenses.filter(r=>expenseInPeriod(r,filterMode,inputMonth,inputStart,inputEnd)),expenseNet=periodExpenses.reduce((s,r)=>s+expenseSignedAmount(r),0),expenseShipping=periodExpenses.filter(r=>r.type==='shipping').reduce((s,r)=>s+Number(r.amount||0),0),expenseOther=periodExpenses.filter(r=>r.type==='other').reduce((s,r)=>s+Number(r.amount||0),0),expenseDiscount=periodExpenses.filter(r=>r.type==='discount').reduce((s,r)=>s+Number(r.amount||0),0)
  const currentCostMap=Object.fromEntries(products.map(p=>[p.id,Number(p.cost||0)])),currentCatMap=Object.fromEntries(products.map(p=>[p.id,p.category||'other']))
  const validOrders=orders.filter(o=>o.status!=='cancelled'),shippedOrders=validOrders.filter(o=>o.status==='shipped'),cancelledOrders=orders.filter(o=>o.status==='cancelled')
  const orderValue=validOrders.reduce((s,o)=>s+effectiveOrderAmount(o),0),shippedGrossRevenue=shippedOrders.reduce((s,o)=>s+Number(o.total_amount||0),0),shippedRefundAmount=shippedOrders.reduce((s,o)=>s+Number(o.refund_amount||0),0),shippedRevenue=shippedOrders.reduce((s,o)=>s+effectiveOrderAmount(o),0),shippedCost=shippedOrders.reduce((s,o)=>s+orderSnapshotCost(o,currentCostMap),0),baseProfit=shippedRevenue-shippedCost,adjustedProfit=baseProfit-expenseNet,adjustmentIsDiscount=expenseNet<0,adjustmentLabel=adjustmentIsDiscount?'折讓淨額':'其他費用淨額',adjustmentDisplay=adjustmentIsDiscount?Math.abs(expenseNet):expenseNet
  const collectedAmount=validOrders.filter(o=>['paid','partial_refund','refunded'].includes(o.payment_status)).reduce((s,o)=>s+effectiveOrderAmount(o),0),outstandingAmount=validOrders.filter(o=>o.payment_status==='unpaid').reduce((s,o)=>s+effectiveOrderAmount(o),0),refundAmount=validOrders.reduce((s,o)=>s+Number(o.refund_amount||0),0),cancelledAmount=cancelledOrders.reduce((s,o)=>s+Number(o.total_amount||0),0),supplierPaidCost=validOrders.filter(o=>o.payable_status==='paid').reduce((s,o)=>s+orderSnapshotCost(o,currentCostMap),0),payableOutstanding=validOrders.filter(o=>o.payable_status!=='paid').reduce((s,o)=>s+orderSnapshotCost(o,currentCostMap),0),paidNotArrived=validOrders.filter(o=>o.payable_status==='paid'&&(o.items||[]).some(i=>Number(i.arrived_qty||0)<Number(i.qty||0))).reduce((s,o)=>s+orderSnapshotCost(o,currentCostMap),0),arrivedNotPaid=validOrders.filter(o=>o.payable_status!=='paid'&&(o.items||[]).length>0&&(o.items||[]).every(i=>Number(i.arrived_qty||0)>=Number(i.qty||0))).reduce((s,o)=>s+orderSnapshotCost(o,currentCostMap),0),netCashFlow=collectedAmount-supplierPaidCost-expenseNet
  const trendData=useMemo(()=>{const map={};shippedOrders.forEach(o=>{const d=new Date(o.order_date),k=filterMode==='all'?`${d.getFullYear()}/${d.getMonth()+1}月`:`${d.getMonth()+1}/${d.getDate()}`;map[k]=(map[k]||0)+effectiveOrderAmount(o)});return Object.entries(map).map(([date,amount])=>({date,amount}))},[shippedOrders,filterMode])
  const topProds=useMemo(()=>{const map={};validOrders.forEach(o=>(o.items||[]).forEach(i=>{const k=i.product_id||i.id||i.product_name||i.name;if(!map[k])map[k]={name:i.product_name||i.name||'未命名商品',qty:0};map[k].qty+=Number(i.qty||0)}));return Object.values(map).sort((a,b)=>b.qty-a.qty).slice(0,8).map(r=>({...r,chartName:r.name.length>12?`${r.name.slice(0,12)}…`:r.name}))},[validOrders])
  const catData=useMemo(()=>{const map={};validOrders.forEach(o=>(o.items||[]).forEach(i=>{const c=i.category||currentCatMap[i.product_id||i.id]||'other';map[c]=(map[c]||0)+Number(i.sale_price??i.price??0)*Number(i.qty||0)}));return Object.entries(map).map(([c,value])=>({name:CAT_LABELS[c]||c,value,color:CAT_COLORS[c]||'#999'}))},[validOrders,currentCatMap])
  const filteredProducts=products.filter(p=>p.active!==false&&p.name.toLowerCase().includes(prodSearch.toLowerCase()))
  const trackBuyers=useMemo(()=>{if(!trackProd)return[];const map={};validOrders.forEach(o=>{const matches=(o.items||[]).filter(i=>(i.product_id||i.id)===trackProd.id||(i.product_name||i.name)===trackProd.name);if(!matches.length)return;const k=o.customer_id||`${o.customer_name}|${o.customer_phone_last2||''}`;if(!map[k])map[k]={name:o.customer_name,phone_last2:o.customer_phone_last2||'',qty:0,pending:0,total:0};matches.forEach(i=>{const q=Number(i.qty||0);map[k].qty+=q;if(o.status==='pending')map[k].pending+=q;map[k].total+=Number(i.sale_price??i.price??0)*q})});return Object.values(map).sort((a,b)=>b.qty-a.qty)},[trackProd,validOrders])
  const supplierRows=useMemo(()=>{const map={};validOrders.forEach(o=>(o.items||[]).forEach(i=>{const supplier=i.supplier||'未指定供應商';if(!map[supplier])map[supplier]={supplier,total:0,outstanding:0,adjustments:0};const fallback=currentCostMap[i.product_id||i.id]??0,cost=Number(i.cost_price??fallback)*Number(i.qty||0);map[supplier].total+=cost;if(o.payable_status!=='paid')map[supplier].outstanding+=cost}));periodExpenses.forEach(e=>{if(!map[e.supplier])map[e.supplier]={supplier:e.supplier,total:0,outstanding:0,adjustments:0};map[e.supplier].adjustments+=expenseSignedAmount(e)});return Object.values(map).sort((a,b)=>(b.outstanding+b.adjustments)-(a.outstanding+a.adjustments))},[validOrders,currentCostMap,periodExpenses])
  const monthlyRows=useMemo(()=>{const map={};shippedOrders.forEach(o=>{const k=monthKey(o.order_date);if(!map[k])map[k]={month:k,revenue:0,cost:0,adjustments:0};map[k].revenue+=effectiveOrderAmount(o);map[k].cost+=orderSnapshotCost(o,currentCostMap)});expenses.forEach(e=>{if(!map[e.month])map[e.month]={month:e.month,revenue:0,cost:0,adjustments:0};map[e.month].adjustments+=expenseSignedAmount(e)});return Object.values(map).sort((a,b)=>a.month.localeCompare(b.month)).map(r=>({...r,profit:r.revenue-r.cost-r.adjustments}))},[shippedOrders,currentCostMap,expenses])
  const periodLabel=filterMode==='all'?'全部期間':filterMode==='month'?inputMonth:`${inputStart||'?'}-${inputEnd||'?'}`

  return <div className="animate-fade">
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20,flexWrap:'wrap',gap:12}}><div><h2 style={{fontSize:22,fontWeight:800}}>銷售與財務報表</h2><p style={{color:'var(--text-secondary)',fontSize:13,marginTop:2}}>已納入每月運費、其他費用與退費折讓</p></div><div style={{display:'flex',gap:7}}><button className="btn btn-ghost" onClick={()=>exportCsv(validOrders,periodExpenses,`group-buy-${periodLabel}.csv`)}><Download size={13}/>CSV</button><button className="btn btn-ghost" onClick={()=>window.print()}><Printer size={14}/>列印</button></div></div>
    <div style={{background:'var(--surface)',borderRadius:'var(--radius)',padding:'14px 16px',marginBottom:18,display:'flex',gap:12,flexWrap:'wrap',alignItems:'center',boxShadow:'var(--shadow-sm)'}}>{[['month','指定月份'],['range','自訂區間'],['all','全部歷史']].map(([v,l])=><button key={v} className={`btn btn-sm ${filterMode===v?'btn-primary':'btn-ghost'}`} onClick={()=>setFilterMode(v)}>{l}</button>)}{filterMode==='month'&&<input type="month" value={inputMonth} onChange={e=>setInputMonth(e.target.value)}/>} {filterMode==='range'&&<><input type="date" value={inputStart} onChange={e=>setInputStart(e.target.value)}/><span>〜</span><input type="date" value={inputEnd} onChange={e=>setInputEnd(e.target.value)}/></>}<span style={{marginLeft:'auto',color:'var(--text-muted)',fontSize:12}}>{loading?'讀取中...':`${orders.length} 筆訂單／${periodExpenses.length} 筆其他費用`}</span></div>
    {error&&<div style={{background:'var(--rose-light)',color:'var(--rose)',padding:12,borderRadius:8,marginBottom:14}}>{error}</div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:12,marginBottom:18}}>{[['有效訂單總額',orderValue,ReceiptText,'linear-gradient(135deg,#6366f1,#4338ca)'],['已出貨營收',shippedRevenue,DollarSign,'linear-gradient(135deg,#10b981,#059669)'],['未收款',outstandingAmount,WalletCards,'linear-gradient(135deg,#f59e0b,#d97706)'],['商品毛利',baseProfit,TrendingUp,'linear-gradient(135deg,#14b8a6,#0f766e)'],[adjustmentLabel,adjustmentDisplay,Truck,'linear-gradient(135deg,#64748b,#475569)'],['調整後毛利',adjustedProfit,TrendingUp,'linear-gradient(135deg,#8b5cf6,#6d28d9)'],['客戶退款',refundAmount,Package,'linear-gradient(135deg,#f43f5e,#be123c)']].map(([label,value,Icon,bg])=><div key={label} className="stat-card" style={{background:bg}}><div style={{fontSize:11,fontWeight:700,opacity:.8}}>{label}</div><div style={{fontSize:21,fontWeight:900,marginTop:5}}>{loading?'—':(label==='折讓淨額'?signedMoney(value):money(value))}</div><Icon size={27} style={{position:'absolute',right:14,top:'50%',transform:'translateY(-50%)',opacity:.22}}/></div>)}</div>
    <div style={{background:'linear-gradient(135deg,#eff6ff,#f5f3ff)',border:'1px solid #c7d2fe',borderRadius:14,padding:'14px 16px',marginBottom:18,color:'var(--text-secondary)'}}>
      <div style={{fontWeight:900,color:'var(--text-primary)',fontSize:14,marginBottom:10}}>🧮 毛利怎麼算？</div>
      <div style={{display:'grid',gap:8,fontSize:12,lineHeight:1.7}}>
        <div><strong style={{color:'#059669'}}>① 已出貨營收</strong>＝原已出貨銷售額 {money(shippedGrossRevenue)} − 客戶退款 {money(shippedRefundAmount)} ＝ <strong>{money(shippedRevenue)}</strong><br/><span style={{color:'#b45309'}}>註：客戶退款已在這一步扣除，後面計算毛利時不會再扣第二次。</span></div>
        <div><strong style={{color:'#0f766e'}}>② 商品毛利</strong>＝已出貨營收 {money(shippedRevenue)} − 已出貨商品成本 {money(shippedCost)} ＝ <strong>{money(baseProfit)}</strong></div>
        <div><strong style={{color:'#6d28d9'}}>③ 調整後毛利</strong>＝商品毛利 {money(baseProfit)} − 運費 {money(expenseShipping)} − 其他費用 {money(expenseOther)} ＋ 供應商退費折讓 {money(expenseDiscount)} ＝ <strong style={{color:'#6d28d9'}}>{money(adjustedProfit)}</strong></div>
      </div>
      <div style={{marginTop:10,paddingTop:10,borderTop:'1px dashed #c7d2fe',fontSize:11}}>本期{adjustmentIsDiscount?<>折讓大於其他費用，因此顯示 <strong style={{color:'#059669'}}>折讓淨額 {signedMoney(adjustmentDisplay)}</strong></>:<>費用高於折讓，因此顯示 <strong>其他費用淨額 {money(adjustmentDisplay)}</strong></>}。取消金額 {money(cancelledAmount)} 不計入營收與毛利。</div>
    </div>
    <div className="tabs" style={{marginBottom:18}}><button className={`tab ${activeTab==='summary'?'active':''}`} onClick={()=>setActiveTab('summary')}>📊 銷售分析</button><button className={`tab ${activeTab==='finance'?'active':''}`} onClick={()=>setActiveTab('finance')}>💰 財務 / 損益</button></div>
    {activeTab==='summary'&&<><div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:14,marginBottom:18}}><div className="card"><div className="card-header" style={{fontWeight:700}}>📈 已出貨營收趨勢</div><div style={{padding:'16px 8px'}}>{trendData.length===0?<div className="empty-state">此期間無已出貨資料</div>:<ResponsiveContainer width="100%" height={220}><LineChart data={trendData}><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={v=>[money(v),'已出貨營收']}/><Line type="monotone" dataKey="amount" stroke="#6366f1" strokeWidth={2.5}/></LineChart></ResponsiveContainer>}</div></div><div className="card"><div className="card-header" style={{fontWeight:700}}>🏷️ 分類佔比</div><div style={{padding:'16px 8px'}}>{catData.length===0?<div className="empty-state">無資料</div>:<ResponsiveContainer width="100%" height={220}><PieChart><Pie data={catData} cx="50%" cy="50%" outerRadius={76} dataKey="value" label={({name,percent})=>`${name} ${Math.round(percent*100)}%`} labelLine={false} fontSize={10}>{catData.map((e,i)=><Cell key={`${e.name}-${i}`} fill={e.color}/>)}</Pie><Tooltip formatter={v=>[money(v)]}/></PieChart></ResponsiveContainer>}</div></div></div><div className="card" style={{marginBottom:18}}><div className="card-header" style={{fontWeight:700}}>🏆 熱銷商品 Top 8</div><div style={{padding:'16px 8px'}}>{topProds.length===0?<div className="empty-state">無資料</div>:<ResponsiveContainer width="100%" height={230}><BarChart data={topProds} layout="vertical"><XAxis type="number"/><YAxis dataKey="chartName" type="category" width={115}/><Tooltip/><Bar dataKey="qty" fill="#6366f1"/></BarChart></ResponsiveContainer>}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div className="card"><div className="card-header" style={{fontWeight:700}}>🔍 商品買家追蹤</div><div className="card-body"><div className="search-input-wrap"><Search size={14}/><input value={prodSearch} onChange={e=>setProdSearch(e.target.value)} placeholder="搜尋商品..." style={{padding:'8px 8px 8px 32px',width:'100%'}}/></div><div style={{maxHeight:300,overflowY:'auto'}}>{filteredProducts.map(p=><div key={p.id} onClick={()=>setTrackProd(p)} style={{padding:'8px 10px',cursor:'pointer',background:trackProd?.id===p.id?'var(--indigo-light)':'transparent'}}>{p.name}</div>)}</div></div></div><div className="card"><div className="card-header" style={{fontWeight:700}}>{trackProd?`${trackProd.name} — 買家名單`:'請選商品'}</div><div className="table-container"><table><thead><tr><th>客戶</th><th>末碼</th><th>總數</th><th>未出</th><th>金額</th></tr></thead><tbody>{trackBuyers.map((b,i)=><tr key={`${b.name}-${i}`}><td>{b.name}</td><td>{b.phone_last2||'—'}</td><td>{b.qty}</td><td>{b.pending||'—'}</td><td>{money(b.total)}</td></tr>)}</tbody></table></div></div></div></>}
    {activeTab==='finance'&&<><div style={{background:'var(--amber-light)',border:'1px solid #fde68a',borderRadius:10,padding:'10px 12px',marginBottom:14,fontSize:12,color:'#92400e'}}>💡 供應商付款與到貨是兩條獨立流程：付款完成代表錢已實際匯出；到貨只代表商品收到。『已付未到貨』可用來追蹤預付／在途貨款，『到貨未付款』則代表尚欠廠商。</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginBottom:16}}>{[['應收帳款（未收款）',outstandingAmount,false],['應付商品成本',payableOutstanding,false],['已付供應商商品成本',supplierPaidCost,false],['已付未到貨',paidNotArrived,false],['到貨未付款',arrivedNotPaid,false],[adjustmentLabel,adjustmentDisplay,adjustmentIsDiscount],['現金流淨額',netCashFlow,false]].map(([l,v,isPositiveAdjustment])=><div key={l} style={{background:'var(--surface-2)',borderRadius:10,padding:14}}><div style={{fontSize:11,fontWeight:700}}>{l}</div><div style={{fontSize:20,fontWeight:900,marginTop:5,color:isPositiveAdjustment?'var(--emerald)':'inherit'}}>{isPositiveAdjustment?signedMoney(v):money(v)}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div className="card"><div className="card-header" style={{fontWeight:700}}>🏭 供應商成本與其他費用</div><div className="table-container"><table><thead><tr><th>供應商</th><th>商品成本</th><th>未付商品</th><th>費用／折讓淨額</th></tr></thead><tbody>{supplierRows.map(r=><tr key={r.supplier}><td>{r.supplier}</td><td>{money(r.total)}</td><td>{money(r.outstanding)}</td><td style={{fontWeight:800,color:r.adjustments>0?'var(--rose)':'var(--emerald)'}}>{r.adjustments<0?`折讓 ${signedMoney(Math.abs(r.adjustments))}`:money(r.adjustments)}</td></tr>)}</tbody></table></div></div><div className="card"><div className="card-header" style={{fontWeight:700}}>📆 月損益（已出貨）</div><div className="table-container"><table><thead><tr><th>月份</th><th>營收</th><th>商品成本</th><th>費用／折讓淨額</th><th>調整後毛利</th></tr></thead><tbody>{monthlyRows.map(r=><tr key={r.month}><td>{r.month}</td><td>{money(r.revenue)}</td><td>{money(r.cost)}</td><td>{r.adjustments<0?signedMoney(Math.abs(r.adjustments)):money(r.adjustments)}</td><td style={{fontWeight:800,color:r.profit>=0?'var(--emerald)':'var(--rose)'}}>{money(r.profit)}</td></tr>)}</tbody></table></div></div></div></>}
  </div>
}
