from pathlib import Path

p = Path('src/pages/Products.jsx')
s = p.read_text()

def repl(old,new):
    global s
    if old not in s:
        raise SystemExit('pattern not found:\n'+old[:180])
    s=s.replace(old,new,1)

repl("const EMPTY_FORM = { name:'',price:'',cost:'',category:'other',supplier:'',note:'',spec_mode:'none',spec_colors:[],spec_sizes:[],spec_flavors:[],price_options:[],price_label_input:'',price_value_input:'',price_cost_input:'',color_input:'',size_input:'',flavor_input:'' }",
"const EMPTY_FORM = { name:'',price:'',cost:'',pricing_mode:'single',category:'other',supplier:'',note:'',spec_mode:'none',spec_colors:[],spec_sizes:[],spec_flavors:[],price_options:[],price_label_input:'',price_value_input:'',price_cost_input:'',color_input:'',size_input:'',flavor_input:'' }")

repl("function PriceOptionsEditor({form,setForm}){const[open,setOpen]=useState(false);const count=(form.price_options||[]).length;",
"function PriceOptionsEditor({form,setForm}){const count=(form.price_options||[]).length;const[open,setOpen]=useState(()=>form.pricing_mode==='options'&&count===0);")

repl("<label>成本（可選）</label>","<label>成本 *</label>")
repl("<div style={{fontSize:12,color:'#92400e',marginBottom:10,fontWeight:600}}>有設定時，下單需選擇組合；數量 1 代表 1 組。例如：一盒500克 200元、一箱5公斤 1800元。</div>","<div style={{fontSize:12,color:'#92400e',marginBottom:10,fontWeight:600}}>多規格商品請在每一組分別輸入售價與成本；數量 1 代表 1 組。例如：小豆漿 40元（成本28）、黑芝麻 50元（成本36）。</div>")

repl("function openEdit(p){setForm({name:p.name,price:p.price,cost:p.cost,category:p.category||'other'",
"function openEdit(p){setForm({name:p.name,price:p.price,cost:p.cost,pricing_mode:(p.pricing_mode==='options'||(p.price_options||[]).length>0)?'options':'single',category:p.category||'other'")

repl("  const profit=p=>Number(p.price||0)-Number(p.cost||0);const margin=p=>Number(p.price||0)>0?Math.round(profit(p)/Number(p.price)*100):0\n  async function save(){\n    if(!form.name.trim()||form.price===''||form.cost===''){toast('請填寫名稱、售價與成本','error');return}setSaving(true)\n    try{if(await ProductsAPI.isDuplicate(form.name.trim(),editId)){toast(`商品「${form.name}」已存在`,'error');return}const payload={name:form.name.trim(),price:Number(form.price),cost:Number(form.cost),category:form.category,supplier:form.supplier.trim(),note:form.note.trim(),spec_mode:form.spec_mode||'none',spec_colors:form.spec_colors||[],spec_sizes:form.spec_sizes||[],spec_flavors:form.spec_flavors||[],price_options:(form.price_options||[]).map(o=>({label:String(o.label||'').trim(),price:Number(o.price||0),cost:o.cost===''||o.cost==null?'':Number(o.cost)}))};",
"  const optionValues=(p,field)=>(p.price_options||[]).map(o=>Number(o[field])).filter(Number.isFinite)\n  const rangeText=(p,field)=>{const vals=optionValues(p,field);if(!vals.length)return `NT$${Number(p[field]||0).toLocaleString()}`;const min=Math.min(...vals),max=Math.max(...vals);return min===max?`NT$${min.toLocaleString()}`:`NT$${min.toLocaleString()}～${max.toLocaleString()}`}\n  const optionProfits=p=>(p.price_options||[]).map(o=>Number(o.price||0)-Number(o.cost||0))\n  const profit=p=>Number(p.price||0)-Number(p.cost||0);const margin=p=>Number(p.price||0)>0?Math.round(profit(p)/Number(p.price)*100):0\n  async function save(){\n    if(!form.name.trim()){toast('請填寫商品名稱','error');return}\n    const multi=form.pricing_mode==='options'\n    if(!multi&&(form.price===''||form.cost==='')){toast('單一售價商品請填寫售價與成本','error');return}\n    if(multi&&(form.price_options||[]).length===0){toast('多規格／組合價商品請至少建立 1 組價格','error');return}\n    if(multi&&(form.price_options||[]).some(o=>String(o.label||'').trim()===''||o.price===''||o.price==null||o.cost===''||o.cost==null)){toast('每個組合都必須填寫名稱、售價與成本','error');return}\n    setSaving(true)\n    try{if(await ProductsAPI.isDuplicate(form.name.trim(),editId)){toast(`商品「${form.name}」已存在`,'error');return}const cleanOptions=(form.price_options||[]).map(o=>({label:String(o.label||'').trim(),price:Number(o.price||0),cost:o.cost===''||o.cost==null?'':Number(o.cost)}));const basePrice=multi?Math.min(...cleanOptions.map(o=>o.price)):Number(form.price);const baseCost=multi?Math.min(...cleanOptions.map(o=>Number(o.cost||0))):Number(form.cost);const payload={name:form.name.trim(),price:basePrice,cost:baseCost,pricing_mode:multi?'options':'single',category:form.category,supplier:form.supplier.trim(),note:form.note.trim(),spec_mode:form.spec_mode||'none',spec_colors:form.spec_colors||[],spec_sizes:form.spec_sizes||[],spec_flavors:form.spec_flavors||[],price_options:multi?cleanOptions:[]};")

old="      <div className=\"form-group\"><label>商品名稱 *</label><input value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className=\"form-group\"><label>售價 (NT$) *</label><input type=\"number\" min=\"0\" value={form.price} onChange={e=>setForm(p=>({...p,price:e.target.value}))}/></div><div className=\"form-group\"><label>成本 (NT$) *</label><input type=\"number\" min=\"0\" value={form.cost} onChange={e=>setForm(p=>({...p,cost:e.target.value}))}/></div></div>{form.price!==''&&form.cost!==''&&<div style={{background:profit(form)>=0?'var(--emerald-light)':'var(--rose-light)',borderRadius:8,padding:'8px 12px',marginBottom:14,fontSize:13,display:'flex',gap:16}}><TrendingUp size={14}/><span>毛利：<strong>NT${profit(form)}</strong></span><span>利潤率：<strong>{margin(form)}%</strong></span></div>}"
new="      <div className=\"form-group\"><label>商品名稱 *</label><input value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))}/></div><div className=\"form-group\"><label>價格模式</label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><button type=\"button\" onClick={()=>setForm(p=>({...p,pricing_mode:'single'}))} style={{padding:'12px',borderRadius:10,border:`2px solid ${form.pricing_mode!=='options'?'var(--indigo)':'var(--border)'}`,background:form.pricing_mode!=='options'?'var(--indigo-light)':'var(--surface)',fontWeight:800,cursor:'pointer'}}>💵 單一售價</button><button type=\"button\" onClick={()=>setForm(p=>({...p,pricing_mode:'options'}))} style={{padding:'12px',borderRadius:10,border:`2px solid ${form.pricing_mode==='options'?'#f59e0b':'var(--border)'}`,background:form.pricing_mode==='options'?'#fff7ed':'var(--surface)',color:form.pricing_mode==='options'?'#92400e':'inherit',fontWeight:800,cursor:'pointer'}}>🧩 多規格／組合價</button></div></div>{form.pricing_mode!=='options'?<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className=\"form-group\"><label>售價 (NT$) *</label><input type=\"number\" min=\"0\" value={form.price} onChange={e=>setForm(p=>({...p,price:e.target.value}))}/></div><div className=\"form-group\"><label>成本 (NT$) *</label><input type=\"number\" min=\"0\" value={form.cost} onChange={e=>setForm(p=>({...p,cost:e.target.value}))}/></div></div>{form.price!==''&&form.cost!==''&&<div style={{background:profit(form)>=0?'var(--emerald-light)':'var(--rose-light)',borderRadius:8,padding:'8px 12px',marginBottom:14,fontSize:13,display:'flex',gap:16}}><TrendingUp size={14}/><span>毛利：<strong>NT${profit(form)}</strong></span><span>利潤率：<strong>{margin(form)}%</strong></span></div>}</>:<div style={{background:'#fff7ed',border:'1.5px solid #f59e0b',borderRadius:10,padding:'11px 13px',marginBottom:14,color:'#92400e',fontSize:13,fontWeight:700}}>🧩 多規格模式：上方不需要填統一售價／成本，請在下方「組合／包裝價」為每個品項分別填售價與成本。</div>}"
repl(old,new)

repl("<SpecEditor form={form} setForm={setForm}/><PriceOptionsEditor form={form} setForm={setForm}/>","<SpecEditor form={form} setForm={setForm}/>{form.pricing_mode==='options'&&<PriceOptionsEditor form={form} setForm={setForm}/>} ")

repl("<td style={{fontWeight:700}}>NT${Number(p.price||0).toLocaleString()}</td><td>NT${Number(p.cost||0).toLocaleString()}</td><td style={{fontWeight:700,color:profit(p)>=0?'var(--emerald)':'var(--rose)'}}>NT${profit(p).toLocaleString()}</td><td>{margin(p)}%</td>","<td style={{fontWeight:700}}>{rangeText(p,'price')}</td><td>{rangeText(p,'cost')}</td><td style={{fontWeight:700,color:(p.price_options||[]).length?'var(--emerald)':profit(p)>=0?'var(--emerald)':'var(--rose)'}}>{(p.price_options||[]).length?(()=>{const vals=optionProfits(p);const min=Math.min(...vals),max=Math.max(...vals);return min===max?`NT$${min.toLocaleString()}`:`NT$${min.toLocaleString()}～${max.toLocaleString()}`})():`NT$${profit(p).toLocaleString()}`}</td><td>{(p.price_options||[]).length?'依規格':`${margin(p)}%`}</td>")

p.write_text(s)

lp=Path('src/components/Layout.jsx')
ls=lp.read_text().replace("const APP_VERSION = 'v2026.08.22.3'","const APP_VERSION = 'v2026.08.22.4'")
if ls==lp.read_text(): raise SystemExit('version pattern not found')
lp.write_text(ls)
